seed: 42

name: fmnist_unsupervised # Name of the run

input:
  batch_size: 32 # Batch size
  dataset: fmnist # "mnist", "fmnist", "kmnist"

model:
  hidden_dim: 32 # Number of ReLUs per hidden layer

training:
  epochs: 10

  learning_rate: 5e-3 # 1e-1 2e-2
  weight_decay: 0
  momentum: 0.9

  type: unsupervised  # "backpropagation", "supervised", "unsupervised"